### ISSUE TITLE
Onion Launcher sometimes works and sometimes not work.

### ISSUE THREAD

**Issue by Luvmaya** [jimgraygit/Onion#133]
When I try to open Onion Launcher with [MENU] button, 

It sometime open but sometimes not open, just kick me to main menu.

So I try to find reason, but only I found is Launcher open just one time after MiyooMini booting.

Turn on the MM --> Open game --> press [MENU] --> Launcher open

but

press [B] to quit --> Main Menu screen --> Open game --> Press [Menu] --> Menu screen comes, not Launcher.

When I reboot, Launcher comes out, but only 1 time.

I want to show Onion Launcher every time, when I press [MENU].

Someone help me.

**Comment by IllustratedMan-code** [comment]
As far as I can tell, this is intended behavior. Once you press B to quit, you are essentially exiting the launcher for that boot session (power button will no longer go to deep sleep either).  You can trigger the menu as many times as you want as long as you press return to game instead of quit. This makes sense to me as the onion launcher is supposed to be a way to focus on one game at a time.

Does that clear it up for you? Unfortunately, there isn't a way to get the behavior you want unless the launcher is changed by the developers.

**Comment by Luvmaya** [comment]
Thanks, I understand but it seems nonsence for me. It is too easy to press menu button. I just press it by my mistake but... quit game?, tooo easy to quit game.. hmm anyway, I understood, Thanks

**Comment by Julian-MJK** [comment]
Interesting that you say that, because I just opened an issue about that exact problem!  #134 
That means I'm not the only one who has issues with how easy it is to quit, so thanks for your feedback

**Comment by Julian-MJK** [comment]
But yes that's how Onion Launcher intentional behavior, not sure if there's a way around it with the way Onion Launcher is designed.

Think of Onion Launcher as a launcher to hop between your recent games. If you quit it with B, you're out of it until you reboot.
It's for when you turn your Miyoo on and just want to play a recent game, not browse around for one. So find the games you like, boot them up once, and you can see them in Onion Launcher (with arrow left or right).

Maybe a name or description change could help clarify this to new users, "Onion Launcher" kinda confused me at first too because it sounds like an all-encompassing solution, it's why I preferred the "Cartridge" name. What about changing the description of Onion Launcher from **"A custom launcher."** (tells the user nothing) to something like **"Easily hop between recent games."**, that should fit the screen

**Comment by Luvmaya** [comment]
I unveiled that this is normal working, but..I still think it's non-sence, anyway Thanks a lot
