### ISSUE TITLE
BUG: Menu+[Button] always fails if you accidentally hit [Button] a millisecond before Menu (E.g. Select+Menu, opens retroarch but then quits)

### ISSUE THREAD

**Issue by Julian-MJK** [jimgraygit/Onion#135]
If you hit the second button just a tiny bit before you hit the menu button, Onion recognizes what you wanted to do and performs that action (e.g. opening the retroarch menu), **but then also quits, because you didn't hit the menu button first.** 

Menu + Select -> Opens retroarch menu
Select + Menu -> Opens retroarch menu, then instantly quits to Onion Launcher

**Comment by Olywa** [comment]
Just my two cents... I don't agree that this is a bug, the instruction is to press 'menu + select' (in that order, menu first, then select), not to press 'menu & select' (together). I've not run into the issue you describe and not seen any complaints from others.

**Comment by Julian-MJK** [comment]
Most systems that have this kind of functionality have that kind of leniancy, the user is instructed to hit them together so they do that. I've personally seen many people do it my way, by interpreting pressing two buttons as pressing them at the same time, not in some unspoken order, and I've seen that work on every system I can think of. The update has been out for like two days so not seeing any complaints is not necessarily representative.

It also seems like unintentional behavior because the action is performed, brightness is changed or the menu is opened, but then it at the exact same time it just quits. 
What I'm talking about is pressing both button at the same time, which is what can lead to hitting menu a microsecond after the second button and thus in the wrong order.

**Comment by DaPiMan** [comment]
I agree with @Julian-MJK I also experienced the Retroarch menu appear and instantly close the game doing the menu + select combo and purely because I had always read the "+" as hitting the buttons together not button 1 then button 2. 

I also noticed that the menu button by itself was an issue for me using MAME Arcade games. I would tap it previously to get the MAME game menu to pop up and noticed the game instantly quitting after this menu appeared and having read that the menu button now exits game I realised I needed to "hold" the menu button a few seconds for menu access and not game quit. 

While not exactly bugs the change is taking some time for muscle memory changes and in between I curse :)

**Comment by Wapp92** [comment]
I Hate the change, why did you make a short press memu button to exit emulator...
Menu + start was fine as is.
The 3.6 menu press combos was fine revert to it.

**Comment by Julian-MJK** [comment]
This seems to have been fixed in the newest update

**Comment by Olywa** [comment]
@Julian-MJK If you are happy with how it functions now you should be able to close the issue mate

**Comment by SirPrimalform** [comment]
It seems strange to me to consider this an issue. If you press 1 and then shift on your keyboard would you expect an exclamation mark? The hotkey is a modifier, while it is held down other buttons take on new functions, exactly like a Shift or Fn key.

**Comment by Sichroteph** [comment]
Closing this issue as it has been solved. Thanks all.
