### ISSUE TITLE
Favorites > Gameinfo  : No boxart

### ISSUE THREAD

**Issue by edgarlim** [jimgraygit/Onion#139]
Is there a way to display boxart at the Favorites > Game.gba > Gameinfo screen? 

For example, for the same game:

Under Console  > GBA > Game.gba > Gameinfo : Boxart shows up
Under Favorites > Game.gba > Gameinfo: Boxart doesn't shows up

Any thoughts?

Thank you

**Comment by Julian-MJK** [comment]
I also have this problem, I'm not sure how the favorites work, if the Miyoo is hardcoded to read boxart from /roms/[SYSTEM]/Imgs/ and so tries to do the same for favorites, or if that's changeable, but it would be great.

**Comment by dwmccoy** [comment]
I would like to point out it does display the box art from the Recent List.

**Comment by benbenco** [comment]
In favorites imgpath is missing instead of recent list, look at the .json for différences :
line in favorite.json : {"label":"Super Chase H.Q. (USA, Europe)","launch":"/mnt/SDCARD/Emu/GB/launch.sh","type":5,"rompath":"/mnt/SDCARD/Emu/GB/../../Roms/GB/Super Chase H.Q. (USA, Europe).zip"}
line in recentlist.json : {"label":"Super Chase H.Q. (USA, Europe)","rompath":"/mnt/SDCARD/Emu/GB/../../Roms/GB/Super Chase H.Q. (USA, Europe).zip",**"imgpath":"/mnt/SDCARD/Emu/GB/../../Roms/GB/Imgs/Super Chase H.Q. (USA, Europe).png"**,"launch":"/mnt/SDCARD/Emu/GB/launch.sh","type":5}
I think the dev team can fix it.

**Comment by ndplymale** [comment]
Still present in v.3.10.6. 

Pretty noticeable issue considering I use my favorites list more than console lists. Hopefully this is a quick fix.

**Comment by Sichroteph** [comment]
We think at changing the game database (for reordering them for example) on the fly, as for the .json files.
I will note it in my to-do list and will close this issue ticket. As it is more a feature request, please feel free to continue in the discussion tab.
However, as we don't have the source code for it, it takes us a tremendous time to add new features, as Miyoo seems to listen to their customer and the mini is a sale hit, I think you should also write to them directly so they add this feature.
