### ISSUE TITLE
Sound is corrupted after auto saving on NEO GEO core (3.71)

### ISSUE THREAD

**Issue by InertiAGruik** [jimgraygit/Onion#142]
Each time you exit a game and the console auto save, when you get back in the game with auto load the sound is corrupted/no sound is heard.
The only solution to get the sound back is to restart the game (and eventually load a manual save if you have one).
A friend and me have the same issue, I don't think it's an isolated problem.

Also is there a way to prevent the onion os to auto save?
I don't find the option to get rid of it.

THX.

**Comment by 7zxkv** [comment]
I confirm this issue !!

**Comment by Jimmy-Z** [comment]
Yeah I'm getting this too.

**Comment by Jimmy-Z** [comment]
You can turn off auto saving in "settings" -> "saving" -> "auto save state“ and ”load state automatically“

**Comment by DaPiMan** [comment]
Are you using UNIBIOS at all? I believe this is a UNIBIOS FBA Bug.

Hit MENU + SELECT, B Button, Settings, Saving, turn off "Auto Save State"

or, if you don't need UNIBIOS functions do:

Hit MENU + SELECT, Options, Neo Geo Mode "MVS", BIOS "(Default MVS Asia/Europe ver. 6 (1 Slot)" and you can leave auto save state on.

**Comment by Jimmy-Z** [comment]
Yes I am using unibios, but I need it 😆

**Comment by 7zxkv** [comment]
in any case, it's bug. (autosaves or not: 3.6 work, 3.7.1 no).

**Comment by Wapp92** [comment]
What rom did you have the issue, i tryed with metal slug 4. Exit by menu + start, relaunch the game and the audio was fine.
I did a clean install.

**Comment by InertiAGruik** [comment]
> What rom did you have the issue, i tryed with metal slug 4. Exit by menu + start, relaunch the game and the audio was fine. I did a clean install.
8man, cyber lip, magician lord, nam75, msg3 a lot of them, an I still have to found one without the sound issue ;)
I just tried with mgs4: same issue and my unibios is configured for this test on EUROPE and AES (console).

**Comment by Sichroteph** [comment]
Should I deactivate unibios by default in Onion ? Is this a matter of finding a new romset ?

**Comment by Olywa** [comment]
I think many folk like to use unibios for NG as you can easily remove censoring from games/change region/etc. 
I don't use it personally but I think of you remove it, people will ask for it back. 
Maybe a note on the wiki that unibios is known to cause missing audio when resuming playback (this can be fixed by restarting the game from the RA menu or by using a regular bios file)?

**Comment by InertiAGruik** [comment]
> I think many folk like to use unibios for NG as you can easily remove censoring from games/change region/etc. I don't use it personally but I think if you remove it, people will ask for it back. Maybe a note on the wiki that unibios is known to cause missing audio when resuming playback (this can be fixed by restarting the game from the RA menu or by using a regular bios file)?

that is not a known problem of unibios, it never do that on pc, I'm using it for years on pc, so there's a problem on the myioo specificaly I think.
This is not a problem of romset neither.
It was working very well on early version of Onion.
Don't deactivate but maybe try to find what can be causing the problem on onion or with the core used?

**Comment by Olywa** [comment]
OK, maybe I wasn't explicit enough but I was implying it's known to cause audio issues _in OnionOS_ (since I was suggesting to update the Onion Wiki).

However, the fact that other genuine NG Bios files do not show this issue does suggest that UniBios is doing something non-standard and as mentioned above this seems to exposed by the Retroarch fbalpha2012_neogeo_libretro.so core (an issue for the RA Core developer, not the Onion Developer).

If it was working on an earlier version (i.e. 3.6) and you have a backup, you could try taking the fbalpha2012_neogeo_libretro.so core from that release and and overwrite your current one.

**Comment by InertiAGruik** [comment]
> UniBios is doing something non-standard

UniBios is doing something non-standard--> that's the purpose of it all :)
I think that the core is maybe the problem yep.

**Comment by Olywa** [comment]
"that's the purpose of it all :)" Well, yes :D but the fact that using MVS/MVS Asia (in UniBios) doesn't bring the issue means they are deviating too much from the normal between modes. I think. Do you have the 3.6 core to try ?

**Comment by dariusdan** [comment]
> What rom did you have the issue, i tryed with metal slug 4. Exit by menu + start, relaunch the game and the audio was fine. I did a clean install.

I confirm this issue happens with mslugx and also tmnt2.
