### ISSUE TITLE
Questioning Future Porting Potential

### ISSUE THREAD

**Issue by JitteryCore** [jimgraygit/Onion#143]
Do you think its possible to port Super Mario 64 or Stardew Valley for Linux? It’s hard doing research on this chipset and it’s potential. Thanks for your time and all the amazing contributions.

**Comment by erazemk** [comment]
> Do you think its possible to port Super Mario 64 or Stardew Valley for Linux?

I can already tell you that you won't be able to play Stardew Valley on the Miyoo Mini, since it requires [at minimum a 2 GHz processor and 2 GB of RAM](https://www.systemrequirementslab.com/cyri/requirements/stardew-valley/13118), which the Mini doesn't have (it only has 128 MB of RAM).

If you want to see the Mini's specs, check out this link: https://github.com/TriForceX/MiyooCFW/wiki/Miyoo-Mini#console-specs

**Comment by JitteryCore** [comment]
Thanks for the answer!
