### ISSUE TITLE
2 future requests; battery % app and music app

### ISSUE THREAD

**Issue by JitteryCore** [jimgraygit/Onion#165]
I can never tell how much battery I have left. It’ll be nice to have a way to see battery percentage. 

I had the music from theme business-Jim gray on for almost an hour. The song is so good lol.

Have you considered a music player or making music videos for the miyoo mini. Sometimes I want to just display this cute device. it’ll be free advertisement.

thanks for the great work!

**Comment by dwmccoy** [comment]
Go here for a Video Player -> https://github.com/steward-fu/miyoo-mini/releases/tag/stock

Get the ffplay app which requires the parasyte app as well.  Unzip the ffplay and place the ffplay folder into the /EMU folder.  Unzip the parasyte app and place the parasyte folder into the /App folder.  Create a /Video folder on the root of the sdcard and place your 480p mp4 files there.

Go here for an MP3 player -> https://github.com/TechDevangelist/gmu/releases

Unzip the GMU and place the gmu folder into the /App folder.  Create a /Music folder on the root of the sdcard and place your MP3 files into it.

**Comment by Frenky81** [comment]
I also hope that the developers can introduce the battery percentage with a much more accurate and gradual estimate because it is very useful.Moreover I hope that they can introduce, by exploiting for example L2 and R2 that are unused in the onion os, the possibility of scrolling through the roms using the initial letter of the alphabet, as happens inside retroarch. In this way the search for games in the folders ,where there are many files, would be much faster and more practical.

**Comment by hungtcs** [comment]
@JitteryCore3.10 version has added these features
- https://github.com/jimgraygit/Onion/releases/tag/20220513

**Comment by Sichroteph** [comment]
Closing now since both requests have been implemented or ported. Thanks all.
