### ISSUE TITLE
[Bug] Favorites disappearing 

### ISSUE THREAD

**Issue by mandorra** [jimgraygit/Onion#173]
I mark some games as favorites, and they go to the list in the main menu as expected. However with time this list gets bugged and names are not displayed correctly (for example it replaces game name by its system) or completely removes games from favorites. It doesn't sounds like the expected behavior to me. I can't provide any more specific reproducibility steps.

**Comment by Wapp92** [comment]
I had that issue on 3.8.2 or 3.8.3, lost my entire fav list. It happen after i press the power button, just a short press. After power it back on fav list had 1 game and name was scramble, all other game were not visible.

**Comment by mandorra** [comment]
That's the case @kirref! Confirmed in 3.9.1 as well. 

We can be safe from the bug for now just avoiding repeated names. However, I would still leave it open just in case somebody cames up with a solution. Maybe appending the system name to the ofending entries?

Game1
Game2 [System1]
Game2 [System2]
Game3

**Comment by Sichroteph** [comment]
Thanks for your interesting findings. I am contacting Miyoo so they can fix this part.

**Comment by robertacurtis** [comment]
I have been having this issue also - caused by changing the name of a game after it has been added as a favourite. The favourites menu will then only display one item ('GameBoy' in my case, even though it is actually a specific game).

Deleting favorites.json fixes the issue, but then you lose your favourites.
