### ISSUE TITLE
Images Not Showing in Some Expert Mode Cores

### ISSUE THREAD

**Issue by JAF62** [jimgraygit/Onion#181]
I scraped all images yesterday using Skraper.
Images are located in \Roms\Corename\Imgs

This works fine in consoles, but in expert mode it isn't for a number of cores.
Main concerns are FBALPHA, MAME2003 & MAME2003PLUS - plus some of the handheld cores

Showing fine for the same cores in Consoles, but not for a handful in Expert Mode.

Does anyone have a fix or workaround for this please?

**Comment by dwmccoy** [comment]
I can confirm this is broken.  Images when placed into the correct folder are not displayed when using cores in the expert menu.

**Comment by JAF62** [comment]
Thanks for confirming

**Comment by Olywa** [comment]
Hi, this might actually be solvable manually. If you check in the RApp/[SystemName] folder you will find a config.json file, here is where the path to your images should be specific. You can edit it accordingly with a text editor (i.e. notepad). 

It is likely pointing to Imgs/[SystemName] (this was the old location) instead of Roms/[SystemName]/Imgs folder.
