### ISSUE TITLE
Frameskip doesn't work correctly for a number of emulators

### ISSUE THREAD

**Issue by no008080** [jimgraygit/Onion#229]
Whenever I try to turn on **Frameskip** (set to **Auto**), the game starts skipping huge chunks of frames by default.
This seems to have been a problem for a while now, as i tested it on all versions since the first one.

Can anyone confirm this issue, or is that an oversight on my part? I haven't found any issues on this topic, open or closed.
I tested it on shauninman's MiniUI, which uses picoarch as an execution layer; it works as intended there.

Firmware: 20220419
OnionOS: v3.10.5

**Comment by Olywa** [comment]
I think the reason you've not found others with this issue is that there is minimal (if any) reason use use frameskip (at least for the default Onion cores). Out of curiosity, for which specific cores/games are you running into issues?

Are you also making other adjustments beyond frameskip (i.e. upscaling)?
Have you tried to achieve what you want with other frameskip settings than auto (i.e. freshhold and interval for which you can set specific preferences).

The retroarch releases are rebuilt for Onion (custom audio/video/input drives, scalers, etc.) so there will likely be be performance differences compared with MinUI & picoarch (in both directions).

**Comment by Olywa** [comment]
Hey again, seems you certainly follow the scene and know your stuff :) 

I believe mGBA was the default OnionOS core in earlier releases and it was switched to gpSP as as a the majority of games performed better (at cost to accuracy as you mentioned) the move was backed by the community. The Onion dev always has his ears open and will take a steer from the community and there are key folk have input with RA & specific cores so there are always continuous improvements, we may see changes for GBA in the future. 

The developer is unlikely to to pick through walls of text here though (he has his hands full already and is doing Onion in his already limited free time). I think you'd do better making your case (and discussing the frameskip) on discord (where the dev will also see it) and to close this issue. Up to you though. 

Custom systems (as you did) are the great thing about Onion, you can really make it how you want. Also, great tips re saves (sharing these on the discord may also earn you brownie points with the community ;)). 

Discord Channel = https://discord.com/channels/529983248114122762/891336865540620338

**Comment by no008080** [comment]
Thank you very much for your concise answers.
I will check out the Discord channel and see if i can post my suggestions there. 

I'm hesitant to close the issue, though, since even with all alternatives, Frameskip itself doesn't really work (or at least on my end, since no one else has confirmed yet).
I think i'll leave this up to the devs, and keep the issue open as a reminder.

**Comment by Edwardphantom** [comment]
please, close, everything if fine here

**Comment by no008080** [comment]
Changing the audio driver in RetroArch's settings to **"sdl"** makes automatic frame skip work. 

Thanks to eggs in the RGH Discord.
