### ISSUE TITLE
Missing nested ROM directories?

### ISSUE THREAD

**Issue by supercom32** [jimgraygit/Onion#246]
Hi Everyone,

I noted that when I had ROM directories which contained multiple child directories inside (Eg. A, B, C, etc) that  they don't seem to show up in Onion OS. Even if I scan for new ROMs, it seems that only some folders arbitrarily show up in the menu. Is this a known limitation? Or is there something specific which causes directory hierarchies to not show up in the GUI? Installing File Explorer and running it shows all directories just fine. It just seems like the front-end doesn't pick them up.

**Comment by no008080** [comment]
![File Explorer_001](https://user-images.githubusercontent.com/97309764/169491199-a4024d96-03d4-4340-b31d-cb97691cf49e.png)

The Miyoo Firmware in general only picks up directories that are specified in the **"config.json"** of the emulator, so to my knowledge that is a limitation, yes.

**Comment by Olywa** [comment]
Onion will pick up sub directories in the rom path defined in the above config.json file but ONLY one level deep. So in the below example, HACKS folder would not bee seen since it s already inside a subdir (but A/B/C should):

--Roms
    --GBA
        --A
        --B
            --HACKS
        --C

As no008080 said, I think this is a limitation of the underlying Miyoo binaries (Onion is just exposing what is already there). Make sure the extlist (also in above config.json) is populated with your correct rom extensions. Also if you are using miyoogamelist.xml (for arcade based systems), directory structures are ignored and all games are shown in a single list.

**Comment by supercom32** [comment]
Thanks! Sounds like it's working as intended then!
