### ISSUE TITLE
Overrides will not be saved in v3.10.5

### ISSUE THREAD

**Issue by ulippus** [jimgraygit/Onion#256]
For different Game Boy games I saved different 'Options > Internal Palette' values via 'Overrides > Save Game Overrides`.

It worked in v3.9.x
SD card is the same new brand.

Is it my fault or is there something broken?

Edit: I did a clean install auf Onion v3.10.5 on a brand new SD-Card and the problem still exists.

**Comment by Olywa** [comment]
I've just tried your scenario (palettes for a GB game in gambatte), also on 3.10.5 and the game overrides changes were not saved post reboot so this does appear to be an issue.

**Comment by Sichroteph** [comment]
The color palette is not an option saved with the core overrides, so selecting it never had an effect on it.
Since it is a core option it should be saved on exit. (it does on my 3.10.5)
If it does not, you can try Quick menu - Options- Manage core options - Save content directory option
If that doesn't work, deleting the .opt file in \Saves\CurrentProfile\config\Gambatte should fix it.
