### ISSUE TITLE
Booting crash

### ISSUE THREAD

**Issue by Bryan7z** [jimgraygit/Onion#291]
Neo Geo games not working
when booting a game the loading screen appears then it kicks me out back to game selection screen like a crash.
However, when booting the game from Retroarch it works, and when using stock miyoo os it also works
the same happens with Mame

v10.3.6

**Comment by Sichroteph** [comment]
Did you follow the recommendation in the github page ?
https://github.com/jimgraygit/Onion/wiki/2.-Onion-Emulators-&-Ports
I have no difficulty in launching a neogeo game, in the main menu or in the launcher.

_Notes: Because neogeo roms can come in different formats (split or non-merged), it's recommended to keep the neogeo.zip bios in the /BIOS folder and the /Roms/NEOGEO folder to ensure best compatibility._

**Comment by Bryan7z** [comment]
Yes I fallowed the github recommendations

and the files are in there degsinated folders they work just not in the menu consoles section
