### ISSUE TITLE
No Console after first install

### ISSUE THREAD

**Issue by Mgiuly** [jimgraygit/Onion#339]
I have a problem with my first install of OnionOS: everything went fine, until the installation process ended, and when I had to choose the consoles to play with, a list of weird names appeared, with prefix "._", and after that list the "good" names was shown. The problem is that no matter if I choose the console with normal or weird name, no console is shown in my Miyoo. I tried to put BIOS in the right folder and copy some games in the Romf folder, but nothing happened. My list remains empty. My Mini V2 is brand new and came with 2022 April firmware just installed. Any suggestion? I tried several times to format and re-install but nothing changed...

**Comment by Olywa** [comment]
Are you setting up the card on a Mac (not PC) ?

**Comment by Mgiuly** [comment]
Yeah, exactly. I read the topics, but in my case the presence or not of ._ (I think related to spotlight) was in-influent for the console view...

**Comment by Olywa** [comment]
I'm not sure how to help as I use only PC (do you have access to one you could use for this?).

Otherwise, I would still suggest it would be worth starting fresh and running the 'dot_clean' on the card (once you've copied the onion setup files to the SD and before inserting into the miyoo mini) as described here: https://github.com/jimgraygit/Onion/issues/93#issuecomment-1092429568

**Comment by Sichroteph** [comment]
Closing as the culprit has been found ..

**Comment by Grendel68DE** [comment]
https://apps.apple.com/de/app/cleanmydrive-2/id523620159?mt=12

As a Mac user, I have had very good experiences with this free app. Each time the SD card is ejected, "._" are automatically deleted.
