### ISSUE TITLE
Clean Install - GBA, SNES, MD Not Working

### ISSUE THREAD

**Issue by Lazarus404** [jimgraygit/Onion#345]
I installed fresh with the latest installation, but I find GBA, SNES and MD doesn't work.  NeoGeo, GB and Arcade work fine.  Not checked every option.  I did notice that the System folder in Retroarch only has a scummvm ini file and nothing else.  I copied the System folder from the SD card that comes with the Miyoo, but that didn't fix it.

**Comment by Olywa** [comment]
This sounds like a Bios issue since all three of these system expect a Bios file. 
Onion stores Bios files in the root 'BIOS' folder (not .retroarch\system). 
Check you have the correct Bios files in the Root 'BIOS' folder as per the wiki: https://github.com/jimgraygit/Onion/wiki/2.-Onion-Emulators-&-Ports 
Note that file names are case sensitive. You may also have to highlight the console and press menu->refresh to refresh your roms.

**Comment by Lazarus404** [comment]
I tried that, too.  Putting `gba_bios.bin` in `SD:/BIOS/` doesn't seem to fix it, either.

**Comment by Lazarus404** [comment]
I tried that, too.  Putting `gba_bios.bin` in `SD:/BIOS/` doesn't seem to fix it, either.

**Comment by Olywa** [comment]
OK and you tried selecting the console and pressing menu-refresh already?

**Comment by Olywa** [comment]
@Lazarus404 any update or can we close this issue? Thanks

**Comment by Lazarus404** [comment]
Yes, please close this. A third and final install got everything working. Many thanks

**Comment by Scandal-UK** [comment]
You're lucky - with my clean install, populated BIOS folder and copied Roms folder from stock card and.. nothing. It scans for roms and finds none. Guess I'll have to find a working launcher like MiniUI instead!

**Comment by Olywa** [comment]
Hi @Lazarus404 Could you change the status to closed for me please, it's something you can do (I'm just a user like yourself so do not have the ability. Many thanks. 
 
@Scandal-UK Enjoy MiniUI - it's a great OS.

**Comment by Lazarus404** [comment]
Done
