### ISSUE TITLE
Can’t add pico-8 games to onion launcher?

### ISSUE THREAD

**Issue by JitteryCore** [jimgraygit/Onion#355]
I tried to add pico-8 games to the onion launcher by favoriting them. It doesn’t work. I can get every other game on any other system to appear on the onion launcher.

Im currently using onion v3.10.6, does the newer updates address this?

Thanks!

**Comment by Olywa** [comment]
This is an issue (on 3.11.2 also). I don't think it's currently possible (or even beneficial) since Pico-8 is using a standalone emulator (FAKE08) which is still in early development and has some limitations (no saves state support being one of them). Perhaps as FAKE08 development progresses it will be possible for the Onion devs to add launcher support for it in the future. 

There is no relationship between favorites and the Onion Launcher by the way but favorites is currently the best way to have quick access to a Pico-8 game.
