### ISSUE TITLE
Sharp X68000 launch.sh is incorrect, causing crash to menu

### ISSUE THREAD

**Issue by RetroBreeze** [jimgraygit/Onion#366]
After installing the Sharp X68000 system via the Onion Installer, the default HOME directory line in `launch.sh` is:

```
HOME=/mnt/SDCARD/RetroArch/ $progdir/../../RetroArch/retroarch -v -L $progdir/px68k_libretro.so "$1"
```

This is incorrect and (naturally) fails to launch the emulator. The correct (and tested working by me) directory is:

```
HOME=/mnt/SDCARD/RetroArch/ $progdir/../../RetroArch/retroarch -v -L $progdir/../../RetroArch/.retroarch/cores/px68k_libretro.so "$1"
```

I'm not sure if this issue is relevant to Onion specifically or another project ([libretro-super](https://github.com/jimgraygit/libretro-super)?). Let me know if I can resubmit this issue elsewhere.

**Comment by Olywa** [comment]
Hey again, thanks for reporting. I think you are the only person I've seen wanting to use this system :D

Good info and your correction makes sense. Keep the ticket here and I'm sure it will be corrected in a future release. 
@Sichroteph one for you ;)

**Comment by RetroBreeze** [comment]
What can I say, I need my SpinDizzy II! If you can point me in the right direction to where this is set I should be able to figure out a PR to fix this. Now worries otherwise. Cheers!

**Comment by Olywa** [comment]
Very kind of you but there is more to this one it seems... the source launch.sh file (before being installed by the installer) is located in: \App\The_Onion_Installer\data\Layer3\X68000\RApp\X68000

...now here's the thing, my copy here (from the onion 3.11.2 release)  is already correct! I just installed X68000 on my device and double checked the launch.sh and it again is correct. 

Which version of Onion are you running? If its the latest and you have not already fixed it in the source path I mentioned above, could your try uninstalling it and reinstalling it via the Onion Installer to see if the issue is still present ?

**Comment by RetroBreeze** [comment]
Alright, so I just set up a brand-new SD with the latest release and you are correct- the config points to the right place and the emulator launched as expected. My primary SD went from 3.9 > 3.10 > 3.11, so I'm not sure if there was some problem updating the installer or something. Regardless, I'm inclined to say that this issue is bunk and I doubt anybody will run into it. I'll close, but feel free to re-open. Sorry for the time wasting!

**Comment by Olywa** [comment]
All good - thanks updating us and for closing ;)
