### ISSUE TITLE
Dreamcast VMU Games not working

### ISSUE THREAD

**Issue by JitteryCore** [jimgraygit/Onion#380]
I recently found out that the Dreamcast VMU has games. I found a few files but they won’t load.
![AB6DF22A-034E-48BE-A85D-CC4633E59117](https://user-images.githubusercontent.com/102029426/173639109-52539a02-26ac-4405-8835-ac74f864ef82.jpeg)
 
 Is there a setting I need to enable or could my file be bad? I tried a few and always get this screen.

**Comment by dwmccoy** [comment]
What is the VMU Mini-Game your trying to play here in the screenshot?

**Comment by JitteryCore** [comment]
> 

Snake, minesweeper, chao adventure 1 & 2, VMU football and slide puzzle.

**Comment by dwmccoy** [comment]
I've never tried this emulator before but here are my findings.  The emulator plays the games too fast to the point you really can't play them.  If you would like to try and play a game, perform the following.  Launch game.  When the distorted / pixelated game screen is displayed, open the Retroarch Menu by pressing Menu+Select.  Choose Close Content.  Choose History and load the game file you just closed.  Choose Run.  The game should now display correctly but it's emulation speed is too fast to enjoy game play.  The Combination of starting the  game, Retroarch Menu, Restart will freeze the emulator and that issue is documented by the developer.  Hope this helped you.

**Comment by dwmccoy** [comment]
I did determine that if you set Automatic Frame delay to ON in the Latency Menu, the game play does indeed slow down.

**Comment by Olywa** [comment]
Hi @JitteryCore, if dwmccoy's solution has resolved your issue please can I ask you to change the status to 'closed'.

These findings and tips will also be added to the wiki.

Many thanks.
