### ISSUE TITLE
[Question]What is the difference between this system and the official system?

### ISSUE THREAD

**Issue by gonejack** [jimgraygit/Onion#383]
Hi, sorry for this issue, but I can't find any features introductions from README.md or Wiki.

**Comment by Olywa** [comment]
Hi there,
  Since this is not an 'issue' or defect I would suggest closing it please and instead raising this in the 'Discussions' tab but maybe this also helps:

Many of the OnionOS specific features are [detailed on the main page](https://github.com/jimgraygit/Onion
)
Youtuber Retro Games Corps also has some excellent [videos covering Onion features](https://www.youtube.com/c/RetroGameCorps/search?query=miyoo%20mini).
