### ISSUE TITLE
Refresh Roms is broken

### ISSUE THREAD

**Issue by MrFaust** [jimgraygit/Onion#391]
Still in Onion 3.11.2
What refreshing roms, Onion will not list newly added games because a couple of lines are missing in several config.json files for the emulators. I went through some of the emulators and added these lines on my setup and the refresh then worked correctly.

Missing lines...
"gamelist":"../../Roms/ROMFOLDERNAME/miyoogamelist.xml",
"extlist":"zip|ZIP|7z|7Z|cue|CUE|chd|CHD|"

**Comment by Olywa** [comment]
Hi there, it would be good to provide a little more info (i.e. which systems where you were having issues, main consoles or experimental).

The Refresh roms is not broken but it does dollow some rules. If the miyoogamelist.xml and extlist fields in the config are left empty, any newly added games will be recognised with a rom refresh.  

By default, miyoogamelist.xml is used and configured only for arcade based systems in the main consoles section (Mame2003+, NeoGeo, CPS1/2/3) since it is useful for renaming & sorting arcade games correctly. 

All expert/experimental cores may require some configuration by the user.

- The extlist tells the OS to ONLY look for those particular extensions, it will disregard anything else. 
- If the extlist is empty then ALL files in that systems Roms folder will be shown in the the game list menu. 
- If the extlist contains already some extensions but you added games with extensions not already included there, then a rom refresh will not find them (since it's been told not to look for those extensions).
- If you are using a miyoogamelist.xml (placed in your systems roms folder) and add games not already included in the xml then a rom refresh will also not find those.

I hope this provides some clarity. I do not believe this to be an issue with Onion and would ask you to please set the status to closed.
