### ISSUE TITLE
Feature Request - Onion Launcher Choosing from Selected Games Instead of History

### ISSUE THREAD

**Issue by kputschko** [jimgraygit/Onion#408]
Hey There,

I love the OS and the Onion Launcher!  I'd love to be able to limit what games to choose from in the Onion Launcher, preferring to choose from a static list of 10 rather than a dynamic list of 10.  I tend to have analysis-paralysis when scrolling through my games, and the Launcher is step in a better direction for me, encouraging me to play some games that I'm already "committed to".

**Comment by Olywa** [comment]
Yeah, this one seems like a 'you' issue rather than an Onion issue ;)
I really don't see the developer making the Launcher list static, it defeats the intention behind it. 

I would suggest you edit the list manually to remove the games you are not interested in, trimming it down to only ~10 that you are, you can do that on your PC by editing the file here: Saves\CurrentProfile\lists\content_history.lpl
