### ISSUE TITLE
Leave the working menu button as in the stock firmware.

### ISSUE THREAD

**Issue by mreeeeq** [jimgraygit/Onion#56]
How can I switch back to call the "stock" menu, when I press the menu button in the game?
Where would the items "Continue", "Save", "Load", "Native", "Menu", "Exit".
And where would the "Load" item, display the picture at the time of saving.

That is, is it possible to return the menu button in the game to the same actions as on the stock firmware, without using RA.

**Comment by thias** [comment]
This is something I also really like about the stock firmware: The dedicated button to bring up a very intuitive menu for simple "pick up and play" that works for everyone. And you do have a sub-menu in there to bring up the advanced stuff. Perfect for the kids and non-techies!

So since I wanted to keep this functionality on my device, I had modified Takiiiiiiii's files to re-introduce the original "ra32.ss" binary that seems to be a RetroArch build where this has been patched in by Miyoo. It seems to work fine with libretro cores from Onion and other places. If you check files such as this one, you'll see how to do that: https://github.com/thias/Miyoo-Mini/blob/main/Emu/SFC/launch.sh

What I did was keep a single copy of the original ra32.ss inside the Emu directory (it gets properly ignored by the frontend) and reference it (and a ra32.cfg file for common options) from each launch.sh. This gives the flexibility of using whatever core you want by putting it in the directory and editing that script, while keeping the original menu. It doesn't seem themable, so you get the original look, which is why I also kept the original theme for my own device.

I still have pending to revisit the Onion and possibly fork it with such changes for the "Emu" part, leaving the "RApp" untouched. But for now I'm happy with a better snes core that doesn't have sound issues, while keeping the original menu, and the kids can easily play without having to remember which button combinations to press to this and that.

**Comment by mreeeeq** [comment]
Thanks for the answer!
I tried to replace the standard retroarch file (4025KB) with the ra32.ss file by renaming it. This creates a ra32.cfg file. I replaced it with the retroarch-nohotkey.cfg file.
What happened to me with these 2 replacements:
- the menu button from the stock firmware began to appear,
- all original aspect ratios were lost,
- there was a black screen when choosing to save earlier (the original firmware showed a screenshot at the time of saving)

I will add ra32.ss to OnionOS and test it with a change in launch.sh for emulators.

**Comment by Sichroteph** [comment]
What is more pick up and play that autosaves ?
You enter immediately in your game where you left.
Then Press menu + start  for quitting the game and make a savestate. I don't understand the need of a menu for this case.

We choose this approach for the convenience of hotkeys. (fast access to savestates, fastforward etc)

**Comment by mreeeeq** [comment]
Manual saving is more convenient for me. If attach a screenshot to this, like in the stock menu, then this makes the user experience more attractive. Even if I have to press a few more buttons.
I can give a girl / friend / child a console without saying a lot of hot buttons. Press 1 button to select options - easier.

**Comment by Sichroteph** [comment]
I understand. The Onion target is indeed not kids. 
Fortunately, the Union UI is in the work and seems to be exactly what you want.
(Check MinUI for the Trimui s)
