### ISSUE TITLE
Onion launcher --> low battery !?

### ISSUE THREAD

**Issue by 7zxkv** [jimgraygit/Onion#86]
Hi,

I did a very simple test:

with the latest version I activated onion launcher. (my battery was fully charged), I just used the console for a few minutes and turned it off. 24 hours later I restart the console: empty battery.

I don't know if onion launcher keeps in ram some information maintained by the battery but obviously there is a problem. My console is new and I used it for around 5-6 hours in all (my battery charger is very high-end so this has nothing to do with it).

Thank you for your attention 

sorry for my poor english ;)

**Comment by Olywa** [comment]
No drain for me when Onion Launcher is enabled. Are you putting the device into 'sleep mode' rather than shutting it down/powering off maybe? 

**If Onion Launcher is enabled:**
Tap power button = sleep mode (top Green LEDs will stay on). 
Menu+Start = Shutdown.  
**If Onion Launcher is disabled** 
Tap power button = sleep mode. 
Holding power (and the press a to confirm) = Shutdown.

Have you tried the same 24hr test with Onion Launcher disabled
