### ISSUE TITLE
GBA Integer+aspect

### ISSUE THREAD

**Issue by itchyd** [jimgraygit/Onion#91]
Integer on + Aspect off does not work for GBA i.e. it is not stretched to fit horizontally.

**Comment by SirPrimalform** [comment]
> Integer on + Aspect off does not work for GBA i.e. it is not stretched to fit horizontally.

In case you're wondering why this was closed, it's probably because the behaviour you're talking about is the correct behaviour.
The biggest integer multiple of the GBA screen possible on the Miyoo Mini is 2x (480x320) and that won't reach the edge of the  Mini's 640x480 screen.
The aspect setting being on or off won't make a difference because the integer scaling automatically maintains aspect ratio.
